baseURL = 'http://savin.org.ru'
languageCode = 'ru'
title = 'Linux engineer blog'
theme = 'hugo-coder'

defaultcontentlanguage = "ru"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Ilya Savin"
  info = "HPC Linux Engineer and beyond"
  description = "my own little webdiary"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2022

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = false

#  customCSS = ["css/custom.css"]
#  customSCSS = ["scss/custom.scss"]
#  customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/imsavin"

[[params.social]]
  name = "Mail"
  icon = "fa fa-envelope fa-2x"
  weight = 2
  url = "mailto:garwallim@gmail.com"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/avial/"

[[params.social]]
  name = "Telegram"
  icon = "fa fa-telegram fa-2x"
  weight = 2
  url = "mailto:garwallim@gmail.com"

[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 4
  url = "https://twitter.com/le_avial/"

# Menu links
[[menu.main]]
  name = "Блог"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Обо мне"
  weight = 2
  url = "about/"
